### ISSUE TITLE
Low quality streaming

### ISSUE THREAD

**Issue by Meamo** [bajicdusko/JavaCVWowzaStarterKit#1]
Hello there, I have tried libstreaming, inde for mobile, vlc streamer and other libraries. I have also just tried this project and compared it with Wowza GoCoder (from google play), and have set the same streaming parameters in both apps. I can see very different qualities. Quality in terms of focus, if you know what I mean. Could you please test gocoder and compare with your app and tell me if you find the same result as mine?

Best regards,
Amir

**Comment by bajicdusko** [comment]
Hello @Meamo , sorry for delay, i was on short vacation.

There are a lot issues on this boilerplate currently, that i'd like to fix and i will in next days. 

What settings do you use for streaming (video dimensions, video bitrate) ? I am using 854x480@700kbps and it is my default settings. Here is a list you could check on for video quality, that youtube is using. https://support.google.com/youtube/answer/2853702?hl=en

GoCoder SDK works just perfectly. no mater what quality and video size you set it will transcode input to the desired video parameters. I am not sure how it works and what they use. As for JavaCV based solution video parameters depends of camera supported parameters and this boilerplate will use nearest supported settings to those you have requested. Additionally, those final parameters might not work if ffmpeg codec (you've set) does not support it. 

As for (auto)focus, you should implement it on your own, since that feature is related to device camera and not to JavaCV. JavaCV just process unput video. So you should implement continuous autofocus or autofocus on touch (or maybe both).

Edit: I have to fix camera switching and torch on/off and i might include autofocus also, but i cannot guarantee when :(

**Comment by vanvd** [comment]
Hi bajicdusko,
thank for your project, but i have a error when build it:
LiveBroadcastActivityPermissionsDispatcher.initCameraWithCheck(this);

please let me know what is LiveBroadcastActivityPermissionsDispatcher.
how i can fix it?
Thank you!

**Comment by bajicdusko** [comment]
https://github.com/bajicdusko/JavaCVWowzaStarterKit/issues/2
